apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/falowomi/argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://aksargocd-dns-bpokq76l.67e8e819-94c8-4631-bbbe-dd968bdaac6f.privatelink.centralus.azmk8s.io
    namespace: myargoapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true